name: Discord Webhook

concurrency: ci-${{ github.ref }}

on:
  workflow_dispatch:

  push:
    branches: [ "main" ] # Default release branch
    paths:
      - 'src/**'   

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  call-workflow-discord-hook:
    uses: Digitalroot-Valheim/.github/.github/workflows/discord.yml@main
    with:
      repo_name: ${{ github.event.repository.name }}
    secrets:
        webhook_url: ${{ secrets.VALHEIM_DISCORD_TITANS_WEBHOOK_URL }}

